# kubernetes/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sidspringbootservice
  namespace: devspring
spec:
  selector:
    app: sidspringboot
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: NodePort

